apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cms
  links:
    - url: https://dashboard.example.com
      title: My Dashboard
      icon: dashboard
  annotations:
    github.com/project-slug: JetteBke/contact-organizer-backend      
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
