version: '3.9'

services:
  corg-frontend:
    image: "cms-fe:1.4"
    ports:
      - "3000:3000" # localhost-port:container-port
  db:
    image: 'postgres:13.2-alpine'
    environment:
      - POSTGRES_DB=cms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres"]
      start_period: "5s"
      interval: "5s"
      retries: 5
    restart: "always"
    volumes:
      - postgres-db:/var/lib/postgresql/data
  corg-backend:
    image: "cms-be:1.9.4"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres-db:
    driver: "local"
